baseURL = "/"
relativeURLs = true
title = "Erik Barfoed"
theme = "erikbarfoed-theme"
defaultContentLanguage = "da"

[languages]
  [languages.da]
    languageName = "Dansk"
    languageCode = "da"
    weight = 1

[params]
  description = "Børne- og ungdomsforfatter"
  default_image = "/images/portrait.jpg"
  author = "Erik Barfoed"
  # Formspree ID tilføjes senere
  # formspree_id = "XXXXXXXX"

[permalinks]
  posts = "/:year/:month/:slug/"
  boeger = "/boeger/:slug/"

[markup.goldmark.renderer]
  unsafe = true