name = "erikbarfoed"
license = "MIT"
licenselink = "https://github.com/yourname/yourproject/blob/master/LICENSE"
description = "Custom theme for erikbarfoed.dk"
homepage = "https://erikbarfoed.dk"
tags = ["author", "minimal", "blog"]
features = ["blog", "books"]
min_version = "0.100.0"

[author]
  name = "Erik Barfoed"
